all: serverM clientA clientB serverA serverB serverC
	
serverM: serverM.cpp
	g++ -std=c++14 serverM.cpp -o serverM
	
clientA: clientA.cpp
	g++ -std=c++14 clientA.cpp -o clientA
	
clientB: clientB.cpp
	g++ -std=c++14 clientB.cpp -o clientB
	
serverA: serverA.cpp
	g++ -std=c++14 serverA.cpp -o serverA
	
serverB: serverB.cpp
	g++ -std=c++14 serverB.cpp -o serverB

serverC: serverC.cpp
	g++ -std=c++14 serverC.cpp -o serverC


	



